[package]
name = "ipfsdc"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[dependencies]
ipfs-client = { git = "https://github.com/Nemo157/ipfs-client-rs" }
futures = "0.1.2"
tokio-core = "0.1.0"
clap = { git = "https://github.com/kbknapp/clap-rs" }
